#!/usr/bin/python3
import pymysql,json
import openpyxl
from openpyxl import Workbook
from datetime import datetime
import smtplib,sys 
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders 
from subprocess import check_output

a=1
fromaddr = "noreply@amrita.ac.in"
toaddr1 = "saishibu38380@gmail.com,"
toaddr2 = "nibikv@gmail.com ,"
toaddr3 = "manu@am.amrita.edu,"
toaddr4 = "binup@am.amrita.edu,"
toaddr5 = "ravishankarm@am.amrita.edu,"
toaddr6 = "anilkumark@am.amrita.edu,"
toaddr7 = "arya.rdjk@gmail.com,"
toaddr8 = "ms.anjana5@gmail.com,"
toaddr9 = "sudarshan.navada@gmail.com,"
toaddr10 = "ganesh.n1412@gmail.com,"


toaddrs=[toaddr1]+[toaddr2]+[toaddr3]+[toaddr4]+[toaddr5]+[toaddr6]+[toaddr7]+[toaddr8]+[toaddr9]
timenow = datetime.now().strftime('%Y-%m-%d_%H:%M:%S')
filename = 'STPReport_'+timenow+'.xlsx'
conn = pymysql.connect(database="AmritaSGM",user="admin",password="admin",host="localhost")
cur = conn.cursor()

wb = Workbook()
ws = wb.active
ws.column_dimensions['A'].width = 20
while a<13:
  cur.execute('SELECT meterName FROM STP where id= %(a)s ;',{'a':a})
  meterName=cur.fetchone()
  meterName=meterName[0]
  print("Report Generating for "+str(meterName))
  cur.execute('SELECT timestamp,VLL ,A, PF, F, W, WH  FROM STPHourData where meterName = %(meterName)s and timestamp >= DATE_SUB(NOW(),INTERVAL 1 DAY) order by ID asc;',{'meterName':meterName})
  results = cur.fetchall()
  
  sheetName = "STP Report - " + str(meterName)
  ws.title=sheetName
  ws.column_dimensions['A'].width = 20
  ws.append(cur.column_names)
  for row in results:
    ws.append(row)
  
  ws=wb.create_sheet("New")   
  a=a+1
  
#wb.remove(ws['Sheet'])
wb.save(filename)
sheetName=wb.get_sheet_names()
print(sheetName)

message = "Namah Shivaya\nReport Generated Successfully on " + timenow
print(message)

# instance of MIMEMultipart 
msg = MIMEMultipart() 

# storing the senders email address 
msg['From'] = 'noreply@amrita.ac.in' 

# storing the receivers email address 
msg['To'] = 'saishibu38380@gmail.com' 

# storing the subject 
msg['Subject'] = datetime.now().strftime('%d-%m-%Y')+" - Daily Report - STP Energy"
msg['CC']=str(toaddr2)+str(toaddr3)+str(toaddr4)+str(toaddr5)+str(toaddr6)+str(toaddr7)+str(toaddr8)+str(toaddr9)+str(toaddr10)
# string to store the body of the mail 
body = str(message)+"\nPlease find the attached STP-Boys Hostel energy usage Report for last 24 hours.\n\nThanks & Regards\nReport Delivery System\nIntelligent Infrastructure Research Group\nCenter for Wireless Networks & Applications\nAmrita Vishwa Vidyapeetham\nAmritapuri Campus\n\n Do not reply to this email. This is an autogenerated report."

# attach the body with the msg instance 
msg.attach(MIMEText(body, 'plain')) 

# open the file to be sent 

attachment = open(filename, "rb") 

# instance of MIMEBase and named as p 
p = MIMEBase('application', 'octet-stream') 

# To change the payload into encoded form 
p.set_payload((attachment).read()) 

# encode into base64 
encoders.encode_base64(p) 

p.add_header('Content-Disposition', "attachment; filename= %s" % filename) 

# attach the instance 'p' to instance 'msg' 
msg.attach(p) 

# creates SMTP session 
s = smtplib.SMTP('smtp.amrita.ac.in', 25) 

# start TLS for security 
s.starttls() 

# Authentication 
s.login('noreply@amrita.ac.in','Amrita@123') 

# Converts the Multipart msg into a string 
text = msg.as_string() 

# sending the mail 
s.sendmail(fromaddr, toaddrs, text) 
#s.sendmail(fromaddr, 'saishibu38380@gmail.com', text) 
#s.sendmail(fromaddr, toaddr3, text) 

# terminating the session 
s.quit() 
print("Email Sent")
delete=check_output(["rm *.xlsx"],shell=1)
